import type { Layouts } from "react-grid-layout";

export const keys = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "k", "l", "n"];

export const HomeLayouts: Layouts = {
    lg: [
        { i: "a", x: 0, y: 0, w: 2, h: 1 },
        { i: "b", x: 2, y: 0, w: 1, h: 1 },
        { i: "f", x: 3, y: 0, w: 1, h: 1 },
        { i: "l", x: 4, y: 0, w: 1, h: 1 },
        { i: "d", x: 0, y: 1, w: 2, h: 1 },
        { i: "e", x: 2, y: 1, w: 1, h: 1 },
        { i: "c", x: 3, y: 1, w: 1, h: 2 },
        { i: "g", x: 0, y: 2, w: 2, h: 1 },
        { i: "h", x: 2, y: 2, w: 1, h: 2 },
        { i: "i", x: 0, y: 3, w: 2, h: 1 },
        { i: "k", x: 0, y: 4, w: 2, h: 1 },
        { i: "n", x: 3, y: 3, w: 2, h: 1 },
    ],
    md: [
        { i: "a", x: 0, y: 0, w: 2, h: 2 },
        { i: "b", x: 2, y: 0, w: 1, h: 1 },
        { i: "f", x: 3, y: 0, w: 1, h: 1 },
        { i: "l", x: 4, y: 0, w: 1, h: 1 },
        { i: "d", x: 0, y: 2, w: 2, h: 1 },
        { i: "h", x: 2, y: 1, w: 1, h: 2 },
        { i: "c", x: 3, y: 1, w: 1, h: 2 },
        { i: "g", x: 0, y: 3, w: 2, h: 2 },
        { i: "i", x: 2, y: 3, w: 1, h: 1 },
        { i: "n", x: 3, y: 3, w: 2, h: 2 },
        { i: "k", x: 0, y: 5, w: 2, h: 1 },
        { i: "e", x: 2, y: 5, w: 1, h: 1 },
    ],
    sm: [
        { i: "a", x: 0, y: 0, w: 2, h: 2 },
        { i: "f", x: 0, y: 2, w: 1, h: 1 },
        { i: "l", x: 1, y: 2, w: 1, h: 1 },
        { i: "c", x: 0, y: 3, w: 1, h: 2 },
        { i: "b", x: 0, y: 5, w: 2, h: 1 },
        { i: "e", x: 0, y: 6, w: 1, h: 1 },
        { i: "h", x: 1, y: 6, w: 1, h: 2 },
        { i: "d", x: 0, y: 8, w: 2, h: 2 },
        { i: "g", x: 0, y: 10, w: 2, h: 2 },
        { i: "i", x: 0, y: 12, w: 2, h: 1 },
        { i: "n", x: 0, y: 13, w: 2, h: 2 },
        { i: "k", x: 0, y: 15, w: 2, h: 2 },
    ],
};

export const AboutLayouts: Layouts = {
    lg: [
        { i: "a", x: 0, y: 0, w: 2, h: 1 },
        { i: "b", x: 2, y: 0, w: 1, h: 1 },
        { i: "c", x: 3, y: 1, w: 1, h: 2, disabled: true },
        { i: "d", x: 0, y: 2, w: 1, h: 1, disabled: true },
        { i: "e", x: 3, y: 0, w: 2, h: 1 },
        { i: "f", x: 1, y: 2, w: 1, h: 1, disabled: true },
        { i: "g", x: 0, y: 3, w: 2, h: 1, disabled: true },
        { i: "h", x: 2, y: 3, w: 1, h: 2, disabled: true },
        { i: "i", x: 0, y: 4, w: 2, h: 1, disabled: true },
        { i: "k", x: 0, y: 1, w: 2, h: 1 },
        { i: "l", x: 2, y: 1, w: 2, h: 1 },
    ],
    md: [
        { i: "a", x: 0, y: 0, w: 2, h: 2 },
        { i: "b", x: 2, y: 0, w: 1, h: 1 },
        { i: "c", x: 3, y: 1, w: 1, h: 2, disabled: true },
        { i: "d", x: 0, y: 2, w: 2, h: 1, disabled: true },
        { i: "e", x: 3, y: 0, w: 2, h: 1 },
        { i: "f", x: 1, y: 5, w: 1, h: 1, disabled: true },
        { i: "g", x: 0, y: 3, w: 2, h: 2, disabled: true },
        { i: "h", x: 2, y: 1, w: 1, h: 2, disabled: true },
        { i: "i", x: 2, y: 3, w: 2, h: 1, disabled: true },
        { i: "k", x: 0, y: 2, w: 2, h: 1 },
        { i: "l", x: 2, y: 2, w: 2, h: 1 },
    ],
    sm: [
        { i: "a", x: 0, y: 2, w: 2, h: 2 },
        { i: "b", x: 0, y: 0, w: 2, h: 1 },
        { i: "c", x: 1, y: 3, w: 1, h: 2, disabled: true },
        { i: "d", x: 0, y: 6, w: 2, h: 2, disabled: true },
        { i: "e", x: 0, y: 3, w: 2, h: 1 },
        { i: "f", x: 1, y: 5, w: 1, h: 1, disabled: true },
        { i: "g", x: 0, y: 8, w: 2, h: 2, disabled: true },
        { i: "h", x: 0, y: 4, w: 1, h: 2, disabled: true },
        { i: "i", x: 0, y: 10, w: 2, h: 1, disabled: true },
        { i: "k", x: 0, y: 5, w: 2, h: 2 },
        { i: "l", x: 0, y: 7, w: 2, h: 1 },
    ],
};

export const ProjectLayouts: Layouts = {
    lg: [
        { i: "a", x: 0, y: 1, w: 2, h: 1, disabled: true },
        { i: "b", x: 2, y: 1, w: 1, h: 1, disabled: true },
        { i: "c", x: 0, y: 0, w: 1, h: 2 },
        { i: "d", x: 3, y: 1, w: 1, h: 1, disabled: true },
        { i: "e", x: 1, y: 1, w: 1, h: 1, disabled: true },
        { i: "f", x: 3, y: 2, w: 1, h: 1, disabled: true },
        { i: "g", x: 0, y: 2, w: 2, h: 1, disabled: true },
        { i: "h", x: 1, y: 0, w: 1, h: 2 },
        { i: "i", x: 2, y: 0, w: 2, h: 1 },
        { i: "k", x: 0, y: 3, w: 2, h: 1, disabled: true },
        { i: "l", x: 2, y: 3, w: 2, h: 1, disabled: true },
        { i: "n", x: 0, y: 4, w: 4, h: 1, disabled: true },
    ],
    md: [
        { i: "a", x: 0, y: 1, w: 2, h: 2, disabled: true },
        { i: "b", x: 2, y: 1, w: 1, h: 1, disabled: true },
        { i: "c", x: 0, y: 0, w: 1, h: 2 },
        { i: "d", x: 3, y: 1, w: 1, h: 1, disabled: true },
        { i: "e", x: 2, y: 4, w: 1, h: 1, disabled: true },
        { i: "f", x: 3, y: 4, w: 1, h: 1, disabled: true },
        { i: "g", x: 0, y: 2, w: 2, h: 2, disabled: true },
        { i: "h", x: 1, y: 0, w: 1, h: 2 },
        { i: "i", x: 2, y: 0, w: 2, h: 1 },
        { i: "k", x: 0, y: 4, w: 2, h: 1, disabled: true },
        { i: "l", x: 2, y: 4, w: 2, h: 1, disabled: true },
        { i: "n", x: 0, y: 5, w: 4, h: 1, disabled: true },
    ],
    sm: [
        { i: "a", x: 0, y: 2, w: 2, h: 2, disabled: true },
        { i: "b", x: 0, y: 4, w: 2, h: 1, disabled: true },
        { i: "c", x: 0, y: 0, w: 1, h: 2 },
        { i: "d", x: 0, y: 8, w: 2, h: 2, disabled: true },
        { i: "e", x: 0, y: 5, w: 1, h: 1, disabled: true },
        { i: "f", x: 1, y: 5, w: 1, h: 1, disabled: true },
        { i: "g", x: 0, y: 6, w: 2, h: 1, disabled: true },
        { i: "h", x: 1, y: 0, w: 1, h: 2 },
        { i: "i", x: 0, y: 2, w: 2, h: 1 },
        { i: "k", x: 0, y: 10, w: 2, h: 1, disabled: true },
        { i: "l", x: 0, y: 11, w: 2, h: 1, disabled: true },
        { i: "n", x: 0, y: 12, w: 2, h: 1, disabled: true },
    ],
};

export const MediaLayouts: Layouts = {
    lg: [
        { i: "a", x: 0, y: 0, w: 2, h: 1, disabled: true },
        { i: "b", x: 2, y: 0, w: 1, h: 1, disabled: true },
        { i: "c", x: 3, y: 0, w: 1, h: 2, disabled: true },
        { i: "d", x: 0, y: 1, w: 2, h: 1 },
        { i: "e", x: 2, y: 1, w: 1, h: 1, disabled: true },
        { i: "f", x: 3, y: 2, w: 1, h: 1, disabled: true },
        { i: "g", x: 0, y: 2, w: 2, h: 1 },
        { i: "h", x: 2, y: 2, w: 1, h: 2, disabled: true },
        { i: "i", x: 0, y: 3, w: 2, h: 1, disabled: true },
        { i: "k", x: 0, y: 4, w: 2, h: 1, disabled: true },
        { i: "l", x: 0, y: 5, w: 2, h: 1, disabled: true },
    ],
    md: [
        { i: "a", x: 0, y: 0, w: 2, h: 2, disabled: true },
        { i: "b", x: 2, y: 0, w: 1, h: 1, disabled: true },
        { i: "c", x: 3, y: 0, w: 1, h: 2, disabled: true },
        { i: "d", x: 0, y: 2, w: 2, h: 1 },
        { i: "e", x: 2, y: 2, w: 1, h: 1, disabled: true },
        { i: "f", x: 3, y: 2, w: 1, h: 1, disabled: true },
        { i: "g", x: 0, y: 3, w: 2, h: 2 },
        { i: "h", x: 2, y: 3, w: 1, h: 2, disabled: true },
        { i: "i", x: 2, y: 5, w: 2, h: 1, disabled: true },
        { i: "k", x: 0, y: 5, w: 2, h: 1, disabled: true },
        { i: "l", x: 0, y: 7, w: 2, h: 1, disabled: true },
    ],
    sm: [
        { i: "a", x: 0, y: 0, w: 2, h: 2, disabled: true },
        { i: "b", x: 0, y: 2, w: 2, h: 1, disabled: true },
        { i: "c", x: 1, y: 3, w: 1, h: 2, disabled: true },
        { i: "d", x: 0, y: 3, w: 2, h: 2 },
        { i: "e", x: 0, y: 5, w: 1, h: 1, disabled: true },
        { i: "f", x: 1, y: 5, w: 1, h: 1, disabled: true },
        { i: "g", x: 0, y: 6, w: 2, h: 2 },
        { i: "h", x: 0, y: 8, w: 1, h: 2, disabled: true },
        { i: "i", x: 0, y: 10, w: 2, h: 1, disabled: true },
        { i: "k", x: 0, y: 13, w: 2, h: 1, disabled: true },
        { i: "l", x: 0, y: 14, w: 2, h: 1, disabled: true },
    ],
};

export const BlogsLayouts: Layouts = {
    lg: [
        { i: "n", x: 0, y: 0, w: 4, h: 3 },
        { i: "a", x: 0, y: 3, w: 2, h: 1, disabled: true },
        { i: "b", x: 2, y: 3, w: 1, h: 1, disabled: true },
        { i: "c", x: 3, y: 3, w: 1, h: 1, disabled: true },
        { i: "d", x: 0, y: 4, w: 2, h: 1, disabled: true },
        { i: "e", x: 2, y: 4, w: 1, h: 1, disabled: true },
        { i: "f", x: 3, y: 4, w: 1, h: 1, disabled: true },
        { i: "g", x: 0, y: 5, w: 2, h: 1, disabled: true },
        { i: "h", x: 2, y: 5, w: 1, h: 1, disabled: true },
        { i: "i", x: 3, y: 5, w: 1, h: 1, disabled: true },
        { i: "k", x: 0, y: 6, w: 2, h: 1, disabled: true },
        { i: "l", x: 2, y: 6, w: 2, h: 1, disabled: true },
    ],
    md: [
        { i: "n", x: 0, y: 0, w: 4, h: 3 },
        { i: "a", x: 0, y: 3, w: 2, h: 2, disabled: true },
        { i: "b", x: 2, y: 3, w: 1, h: 1, disabled: true },
        { i: "c", x: 3, y: 3, w: 1, h: 1, disabled: true },
        { i: "d", x: 0, y: 5, w: 2, h: 1, disabled: true },
        { i: "e", x: 2, y: 4, w: 1, h: 1, disabled: true },
        { i: "f", x: 3, y: 4, w: 1, h: 1, disabled: true },
        { i: "g", x: 0, y: 6, w: 2, h: 2, disabled: true },
        { i: "h", x: 2, y: 5, w: 1, h: 2, disabled: true },
        { i: "i", x: 3, y: 5, w: 2, h: 1, disabled: true },
        { i: "k", x: 0, y: 8, w: 2, h: 1, disabled: true },
        { i: "l", x: 2, y: 8, w: 2, h: 1, disabled: true },
    ],
    sm: [
        { i: "n", x: 0, y: 0, w: 2, h: 4 },
        { i: "a", x: 0, y: 4, w: 2, h: 2, disabled: true },
        { i: "b", x: 0, y: 6, w: 2, h: 1, disabled: true },
        { i: "c", x: 0, y: 7, w: 1, h: 2, disabled: true },
        { i: "d", x: 0, y: 9, w: 2, h: 2, disabled: true },
        { i: "e", x: 0, y: 11, w: 1, h: 1, disabled: true },
        { i: "f", x: 1, y: 11, w: 1, h: 1, disabled: true },
        { i: "g", x: 0, y: 12, w: 2, h: 2, disabled: true },
        { i: "h", x: 0, y: 14, w: 1, h: 2, disabled: true },
        { i: "i", x: 0, y: 16, w: 2, h: 1, disabled: true },
        { i: "k", x: 0, y: 17, w: 2, h: 1, disabled: true },
        { i: "l", x: 0, y: 18, w: 2, h: 1, disabled: true },
    ],
};
